controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

effort_controllers:
  ros__parameters:
    joints:
      - o_rl
      - o_rr
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort